/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Register_Login_Table;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author dam
 */
public class RegisterPage extends javax.swing.JFrame {
    
    /**
     * Creates new form Ejercicio2
     */
    public RegisterPage() {
        initComponents();
        spinner_age.setValue(18);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        button_group_gender = new javax.swing.ButtonGroup();
        label_name = new javax.swing.JLabel();
        text_field_name = new javax.swing.JTextField();
        label_age = new javax.swing.JLabel();
        spinner_age = new javax.swing.JSpinner();
        label_login = new javax.swing.JLabel();
        text_field_login = new javax.swing.JTextField();
        label_password = new javax.swing.JLabel();
        password_field_password = new javax.swing.JPasswordField();
        label_nif = new javax.swing.JLabel();
        text_field_nif = new javax.swing.JTextField();
        label_lastname = new javax.swing.JLabel();
        text_field_lastname = new javax.swing.JTextField();
        label_confirm_password = new javax.swing.JLabel();
        password_field_confirmation = new javax.swing.JPasswordField();
        radio_button_man = new javax.swing.JRadioButton();
        radio_button_woman = new javax.swing.JRadioButton();
        radio_button_other = new javax.swing.JRadioButton();
        check_box_basket = new javax.swing.JCheckBox();
        check_box_squash = new javax.swing.JCheckBox();
        check_box_tenis = new javax.swing.JCheckBox();
        button_register = new javax.swing.JButton();
        button_go_back = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_name.setText("Nombre");

        text_field_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_field_nameActionPerformed(evt);
            }
        });

        label_age.setText("Edad");

        label_login.setText("Login");

        text_field_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_field_loginActionPerformed(evt);
            }
        });

        label_password.setText("Password");

        password_field_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_field_passwordActionPerformed(evt);
            }
        });

        label_nif.setText("N.I.F.");

        text_field_nif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_field_nifActionPerformed(evt);
            }
        });

        label_lastname.setText("Apellidos");

        text_field_lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_field_lastnameActionPerformed(evt);
            }
        });

        label_confirm_password.setText("Confirmar Password");

        button_group_gender.add(radio_button_man);
        radio_button_man.setSelected(true);
        radio_button_man.setText("Hombre");
        radio_button_man.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_button_manActionPerformed(evt);
            }
        });

        button_group_gender.add(radio_button_woman);
        radio_button_woman.setText("Mujer");
        radio_button_woman.setToolTipText("");
        radio_button_woman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_button_womanActionPerformed(evt);
            }
        });

        button_group_gender.add(radio_button_other);
        radio_button_other.setText("Otro");

        check_box_basket.setText("Basket");
        check_box_basket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_box_basketActionPerformed(evt);
            }
        });

        check_box_squash.setText("Squash");

        check_box_tenis.setText("Tenis");

        button_register.setText("Registrarse");
        button_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_registerActionPerformed(evt);
            }
        });

        button_go_back.setText("<- GO BACK");
        button_go_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_go_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(button_go_back, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(label_age, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_field_name, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinner_age, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_login, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_field_login, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password_field_password, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(label_name, javax.swing.GroupLayout.Alignment.LEADING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_confirm_password)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(password_field_confirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button_register, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_nif)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(text_field_nif, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radio_button_man)
                                    .addComponent(radio_button_woman)
                                    .addComponent(radio_button_other))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(check_box_tenis)
                                    .addComponent(check_box_squash)
                                    .addComponent(check_box_basket)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_lastname)
                            .addComponent(text_field_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_name)
                    .addComponent(label_lastname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_field_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_field_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_age)
                    .addComponent(label_nif))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinner_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_field_nif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radio_button_man)
                    .addComponent(check_box_basket))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_login)
                    .addComponent(radio_button_woman)
                    .addComponent(check_box_squash))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_field_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radio_button_other)
                    .addComponent(check_box_tenis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_password)
                    .addComponent(label_confirm_password))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_field_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password_field_confirmation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_register))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(button_go_back)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_field_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_field_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_field_nameActionPerformed

    private void text_field_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_field_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_field_loginActionPerformed

    private void password_field_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_field_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_field_passwordActionPerformed

    private void text_field_nifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_field_nifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_field_nifActionPerformed

    private void text_field_lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_field_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_field_lastnameActionPerformed

    private void radio_button_manActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_button_manActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_button_manActionPerformed

    private void radio_button_womanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_button_womanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_button_womanActionPerformed

    private void check_box_basketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_box_basketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_check_box_basketActionPerformed

    private void button_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_registerActionPerformed
        try {
            // TODO add your handling code here:
            register();
        } catch (IOException ex) {
            Logger.getLogger(RegisterPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button_registerActionPerformed

    private void button_go_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_go_backActionPerformed
        // TODO add your handling code here:
        go_back();
    }//GEN-LAST:event_button_go_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPage().setVisible(true);
            }
        });
    }
    
    public void go_back(){
        Menu menu = new Menu();
        menu.show();
        dispose();
    }
    
    public void register() throws IOException{
        if(!validator()){
            //read_database();
            if(search_database()){
                JOptionPane.showMessageDialog(null, "N.I.F. "+text_field_nif.getText()+" is already on our database");
            } 
            else{
                if(search_login()){
                    JOptionPane.showMessageDialog(null, "Login "+text_field_login.getText()+" is already on our database");
                }
                else{
                    if(!nif_validator()){
                        JOptionPane.showMessageDialog(null, "N.I.F. format is not valid, a valid format is: \n"
                                + "11111111A");
                    }
                    else{
                       if(!password_isValid()){
                        JOptionPane.showMessageDialog(null, "The password must have 8 characters, almost one Mayus, \none number "
                                + "and one of this symbols: \n"
                                + "?, ¿, !, ¡, -, &, +, *");
                        }
                        else{
                            if(!password_validator()){
                                JOptionPane.showMessageDialog(null, "The passwords must be the same");
                            }
                            else{
                                if(!spinner_validator()){
                                    JOptionPane.showMessageDialog(null, "The age is not valid");
                                }
                                else{
                                    JOptionPane.showMessageDialog(null, "All the fields must be filled");
                                }
                            }
                        } 
                    }
                }
            }
        }
        else{
            write_database();
            cleanFields();
        }
        
}
    
    public void cleanFields(){
        text_field_name.setText("");
        text_field_lastname.setText("");
        text_field_login.setText("");
        text_field_nif.setText("");
        spinner_age.setValue(18);
        password_field_password.setText("");
        password_field_confirmation.setText("");
        button_group_gender.clearSelection();
        radio_button_man.setSelected(true);
        check_box_basket.setSelected(false);
        check_box_squash.setSelected(false);
        check_box_tenis.setSelected(false);
    }
    
    public boolean search_login() throws FileNotFoundException, IOException{
        File searchDB = new File("database");

		BufferedReader DBreader = new BufferedReader(new FileReader(searchDB));
		
		String loginToFind = text_field_login.getText();
		String currentLine;
		
		boolean was_found=false;

		while((currentLine = DBreader.readLine()) != null) {
		    // trim newline when comparing with lineToRemove
			String[]all_DB =currentLine.split("_");
                        String login_DB = all_DB[4];
		    if(login_DB.equals(loginToFind)) {
		    	was_found=true;
		    }
		}
		DBreader.close(); 
        return was_found;
    }
    
    public boolean search_database() throws FileNotFoundException, IOException{
        File searchDB = new File("database");

		BufferedReader DBreader = new BufferedReader(new FileReader(searchDB));
		
		String nifToFind = text_field_nif.getText();
		nifToFind=nifToFind.toUpperCase();
		String currentLine;
		
		boolean was_found=false;

		while((currentLine = DBreader.readLine()) != null) {
		    // trim newline when comparing with lineToRemove
			String[]all_DB =currentLine.split("_");
                        String nif_DB = all_DB[3];
		    if(nif_DB.equals(nifToFind)) {
		    	was_found=true;
		    }
		}
		DBreader.close(); 
        return was_found;
    }
    
    public boolean validator(){
        boolean validation=false;
        
        if(!text_field_name.getText().equals("") 
                && !text_field_lastname.getText().equals("")
                && !text_field_nif.getText().equals("")
                && nif_validator()
                && spinner_validator()
                && !text_field_login.getText().equals("")
                && !password_field_password.getText().equals("")
                && !password_field_confirmation.getText().equals("")
                && password_validator()
                && password_isValid()){
            validation=true;
        }
        
        return validation;
    }
    
    public boolean nif_validator(){
        boolean nif_is=false;
        
        if(text_field_nif.getText().length()!=9 || !nif_numbers() || Character.isLetter(text_field_nif.getText().charAt(8))==false){
            nif_is=false;
        }
        else{
            nif_is=true;
        }
        return nif_is;
    }
    
    public boolean nif_numbers(){
        boolean nif_number=false;
        int cont_numbers=0;
        
        for(int i=0; i<((text_field_nif.getText().length())-1); i++){
            char c = text_field_nif.getText().charAt(i);
            if(c=='0'|| c=='1'|| c=='2'|| c=='3'|| c=='4'|| c=='5'|| c=='6'|| c=='7'|| c=='8'|| c=='9'){
                cont_numbers++;
            }
        }
        if(cont_numbers==8){
            nif_number=true;
        }
        
        return nif_number;
    }
    
    public boolean spinner_validator(){
        boolean sp_validator=false;
        if(((int) spinner_age.getValue())<=120 && ((int) spinner_age.getValue())>=18){
            sp_validator=true;
        }
        return sp_validator;
    }
    
    public boolean password_validator(){
        boolean pw_validator=false;
        if(password_field_password.getText().equals(password_field_confirmation.getText())){
            pw_validator=true;
        }
        return pw_validator;
    }
    
    public boolean password_isValid(){
        boolean isValid=false;
        if(password_field_password.getText().length()<8){
            isValid=false;
        }
        if(hasMayus()){
            if(hasNumbers()){
                if(hasSymbols()){
                    isValid=true;
                }
            }
        }
        if(!hasBarraBaja()){
            isValid=false;
        }
        return isValid;
    }
           
    public boolean hasBarraBaja(){
        for(int i=0; i<(password_field_password.getText().length()); i++){
            char c = password_field_password.getText().charAt(i);
            if(c=='_'){
                return false;
            }
        }
        return true;
    }
    
    public boolean hasMayus(){
        for(int i=0; i<(password_field_password.getText().length()); i++){
            char c = password_field_password.getText().charAt(i);
            if(c=='A'|| c=='B'|| c=='C' ||c=='D'|| c=='E'|| c=='F'|| c=='G'|| c=='H'|| c=='I'|| c=='J'|| c=='K'|| c=='L'|| c=='M'
                    || c=='N'|| c=='Ñ'|| c=='O'|| c=='P'|| c=='Q'|| c=='R'|| c=='S'|| c=='T'|| c=='U'|| c=='V'|| c=='W'|| c=='X'
                    || c=='Y'|| c=='Z'){
                return true;
            }
        }
        return false;
    }
    
    public boolean hasNumbers(){
        for(int i=0; i<(password_field_password.getText().length()); i++){
            char c = password_field_password.getText().charAt(i);
            if(c=='0'|| c=='1'|| c=='2'|| c=='3'|| c=='4'|| c=='5'|| c=='6'|| c=='7'|| c=='8'|| c=='9'){
                return true;
            }
        }
        return false;
    }
    
    public boolean hasSymbols(){
        for(int i=0; i<(password_field_password.getText().length()); i++){
            char c = password_field_password.getText().charAt(i);
            if(c=='?'|| c=='¿'|| c=='!'|| c=='¡'|| c=='-'|| c=='&'|| c=='+'|| c=='*'){
                return true;
            }
        }
        return false;
    }
    
    public String gender(){
        String gender=null;
        
        if(radio_button_man.isSelected()){
            gender="MAN";
        }
        else{
            if(radio_button_woman.isSelected()){
                gender="WOMAN";
            }
            else{
                gender="OTHER";
            }
        }
        return gender;
    }
    
    public String deportes(){
        String deportes=null;
        
        if(check_box_basket.isSelected()){
            deportes="BASKET_";
        }
        else{
            deportes="NULL_";
        }
        if(check_box_squash.isSelected()){
            deportes=deportes+"SQUASH_";
        }
        else{
            deportes=deportes+"NULL_";
        }
        if(check_box_tenis.isSelected()){
            deportes=deportes+"TENIS";
        }
        else{
            deportes=deportes+"NULL";
        }
        
        return deportes;
    }
    
    public String newLine(){
        String newLine=
                "\n"+text_field_name.getText().toUpperCase()
                +"_"+text_field_lastname.getText().toUpperCase()
                +"_"+spinner_age.getValue()
                +"_"+text_field_nif.getText().toUpperCase()
                +"_"+text_field_login.getText()
                +"_"+password_field_password.getText()
                +"_"+gender().toUpperCase()
                +"_"+deportes().toUpperCase();
        
        return newLine;
    }
    
    public void write_database(){
        FileWriter database = null;
        PrintWriter pw = null;
        try{
            database = new FileWriter("database", true);
            pw = new PrintWriter(database);
            pw.print(newLine());	
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
           try {
           if (null != database)
              database.close();
           } catch (Exception e2) {
              e2.printStackTrace();
           }
        }
    }
    
    public void read_database() throws FileNotFoundException, IOException{
        File readDB = new File("database");

		BufferedReader db_reader = new BufferedReader(new FileReader(readDB));
		String currentLine;

		while((currentLine = db_reader.readLine()) != null) {
		    // trim newline when comparing with lineToRemove
                    String[]all_DB =currentLine.split("_");
			String name_DB = all_DB[0];
			String last_name_DB = all_DB[1];
			String age_DB = all_DB[2];
			String nif_DB = all_DB[3];
                        String login_DB = all_DB[4];
                        String password_DB = all_DB[5];
                        String gender_DB = all_DB[6];
                        String deportes1_DB = all_DB[7];
                        String deportes2_DB = all_DB[8];
                        String deportes3_DB = all_DB[9];
			System.out.println("Name: "+name_DB);
			System.out.println("Last Name: "+last_name_DB);
			System.out.println("Age: "+age_DB);
			System.out.println("N.I.F.: "+nif_DB);
                        System.out.println("Login: "+login_DB);
                        System.out.println("Password: "+password_DB);
                        System.out.println("Gender: "+gender_DB);
                        System.out.println("Deportes "+deportes1_DB
                        +", "+deportes2_DB+", "+deportes3_DB);
			System.out.println("------------------------");
		}
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_go_back;
    private javax.swing.ButtonGroup button_group_gender;
    private javax.swing.JButton button_register;
    private javax.swing.JCheckBox check_box_basket;
    private javax.swing.JCheckBox check_box_squash;
    private javax.swing.JCheckBox check_box_tenis;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel label_age;
    private javax.swing.JLabel label_confirm_password;
    private javax.swing.JLabel label_lastname;
    private javax.swing.JLabel label_login;
    private javax.swing.JLabel label_name;
    private javax.swing.JLabel label_nif;
    private javax.swing.JLabel label_password;
    private javax.swing.JPasswordField password_field_confirmation;
    private javax.swing.JPasswordField password_field_password;
    private javax.swing.JRadioButton radio_button_man;
    private javax.swing.JRadioButton radio_button_other;
    private javax.swing.JRadioButton radio_button_woman;
    private javax.swing.JSpinner spinner_age;
    private javax.swing.JTextField text_field_lastname;
    private javax.swing.JTextField text_field_login;
    private javax.swing.JTextField text_field_name;
    private javax.swing.JTextField text_field_nif;
    // End of variables declaration//GEN-END:variables
}